version: '2'
services:
  api:
    mem_limit: 2g
    mem_reservation: 240m
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      options:
        max-size: '1m'
        max-file: '3'
