version: '2'
services:
  api:
    container_name: api 
    extends:
      file: docker-compose.shared.yml
      service: api
    build:
      args:
        - DEBUG=1
    volumes:
      - .:/vscode-dockerized-setup
